### ISSUE TITLE
[REQ] Please add *-arr support back

### ISSUE THREAD

**Issue by 8a8al00ey** [by275/plex_autoscan#1]
Would it be possible to add *-arr support back ? This seems to be the most up to date and well coded PAS tool. If not how are you automatically scanning in items ?

**Comment by by275** [comment]
Unfortunately, not possible. I do not use any of *-arrs and have little knowledge to implement connections with them. That's why I removed related-logic. PR always welcomed though.

In my current setup, most of changes for plex media scan rely on ones from google drive.

**Comment by 8a8al00ey** [comment]
Not a problem, might give it a shot. Not really a python dev here but I assume to get this to work with *-arrs will need to do something similar to https://github.com/by275/plex_autoscan/blob/514864e9c9bb1c6cd619e203b12646edf3fecdba/autoscan/utils.py#L367
and
https://github.com/by275/plex_autoscan/blob/514864e9c9bb1c6cd619e203b12646edf3fecdba/autoscan/__main__.py#L322

Are you on any discord servers ?

**Comment by by275** [comment]
I have merged it to master. Would you please make the PR to master again?

**Comment by 8a8al00ey** [comment]
Created #5
