### ISSUE TITLE
[DISCUSSION] Removing from drive cache after processing.

### ISSUE THREAD

**Issue by 8a8al00ey** [by275/plex_autoscan#11]
Hello,
What is your thoughts about removing the item from the drive db after it was processed? Once it is scanned in plex or rejected what is the logic of keeping it in the db ?

**Comment by by275** [comment]
Can't get your point exactly. `cache.db` keeps two tables, one for settings/authorization info about associated google drives (very small size), another for temporary cache to interpret id to directory path. The latter consumes a large part of it and is continuously growing. If this is your concern, yes, it is not optimized and need to be further improved.

However, it seems not easy at the moment. As one of quick fix, we can add an option to cleanup drive cache via api or on startup if its size is larger than user-configured amount.

**Comment by 8a8al00ey** [comment]
Correct the `cache` table of the `cache.db`. Basically once that id/path was processed if it should be removed or possibly after each page token change compares the two to find changes, sends those changes to scan and saves the new changes to the db for the next comparison. So the `cache` table would only contain the current page token changes.

**Comment by by275** [comment]
It's been almost a year since I port/rewrite the google drive module. So hard to recall. Anyway... Changes from google drive Api only provide information about a single file/directory and its parent. Cache in `cache.db` stores this partial info and use it to combine full path. For example, a new file comes in `/show1/episode1.mp4`. Then we only know a name of file `episode1.mp4` and its parent id, not name. So, the name of parent folder would be needed for later use, e.g., when `episode2.mp4` comes in. What I am trying to say is that `cache` table is not for one time use and needs to be preserve after scan finished.

**Comment by 8a8al00ey** [comment]
Was playing around with something basic and something like this seemed to work. It also worked on subsequent changes as cache table the gets populated with the new items data ie parent id, path etc on each change.
```
diff --git a/autoscan/drive.py b/autoscan/drive.py
index e7a7cdf..99543cb 100644
--- a/autoscan/drive.py
+++ b/autoscan/drive.py
@@ -1,6 +1,7 @@
 import logging
 import os
 import sys
+import sqlite3
 import json
 from copy import copy

@@ -591,6 +592,14 @@ class GoogleDrive:
         self._do_callback("items_unwanted", unwanted_file_paths)
         self._do_callback("items_ignored", ignored_file_paths)

+       # Clear the cache after processing changes
+        logger.info("Clearing the cache after processing all changes:")
+        self.cache.clear()
+
+        logger.info("Vacuum the cache.db:")
+        conn=sqlite3.connect('cache.db')
+        conn.close()
+
     def _do_callback(self, callback_type, callback_data):
         if callback_type in self.callbacks and callback_data:
             self.callbacks[callback_type](callback_data)
```

```
2022/09/14 10:02:54 INFO  GOOGLE   [Drive     ]: Added '1L4wAN_XXXXX-' to cache: Sesame Street (1969) - S52E32 - Elmo's Number Adventure XXXXXXX.mkv
2022/09/14 10:02:55 INFO  GOOGLE   [Drive     ]: Added '1ny7XXXXX' to cache: Season 52
2022/09/14 10:02:55 INFO  GOOGLE   [Drive     ]: Added '1q0XXXXXX' to cache: Sesame Street (1969)
2022/09/14 10:02:55 INFO  GOOGLE   [Drive     ]: Added '1CXXXXXXX' to cache: TV
2022/09/14 10:02:55 INFO  GOOGLE   [Drive     ]: Added '1GXXXXXXX' to cache: Media
2022/09/14 10:02:56 INFO  GOOGLE   [Drive     ]: Added '0AXXXXXXX' to cache: TV
2022/09/14 10:02:56 INFO  AUTOSCAN [Drive     ]: Proceeding with scan of 1 file(s) from Google Drive changes: ["TV/Media/TV/Sesame Street (1969)/Season 52/Sesame Street (1969) - S52E32 - Elmo's Number Adventure XXXXXXX.mkv"]
2022/09/14 10:02:56 INFO  PLEX     [Thread-8  ]: Scan request from Google Drive for '/mnt/unionfs2/Media/TV/Sesame Street (1969)/Season 52/Sesame Street (1969) - S52E32 - Elmo's Number Adventure XXXXXXXX.mkv'.
2022/09/14 10:02:56 INFO  GOOGLE   [Drive     ]: Clearing the cache after running all changes:
2022/09/14 10:02:56 INFO  PLEX     [Thread-8  ]: Sleeping for 60 seconds...
2022/09/14 10:02:56 INFO  GOOGLE   [Drive     ]: Vacuum the cache.db:
2022/09/14 10:03:56 INFO  PLEX     [Thread-8  ]: Scan request is now being processed...
2022/09/14 10:03:56 INFO  PLEX     [Thread-8  ]: No 'Plex Media Scanner' processes were found.
2022/09/14 10:03:56 INFO  PLEX     [Thread-8  ]: Plex is available for media scanning - (Server Account: 'enormoz@gmail.com')
2022/09/14 10:03:56 INFO  PLEX     [Thread-8  ]: Sending scan request for '/mnt/unionfs2/Media/TV/Sesame Street (1969)/Season 52'
2022/09/14 10:03:59 INFO  PLEX     [Thread-8  ]: Finished scan!
2022/09/14 10:04:00 INFO  PLEX     [Thread-8  ]: There are 0 queued item(s) remaining.
```

**Comment by by275** [comment]
Vacuum is necessary? Calling `cache.clear()` seems enough. Btw, clearning cache after each of changes still seems too aggressive to me.

**Comment by 8a8al00ey** [comment]
This was more a test to see what would happen. Added vaccum as there were times it didn't clear the disk space after the clear. It wasn't all the time.  I think a good compromise could be a clean db on each start or set some sort of db size limit.  I was more curious on what got stored on each cache dump.

**Comment by 8a8al00ey** [comment]
Are you on discord ?

**Comment by by275** [comment]
Yes, I am in Cloudbox, but not sure how I can find you or let you find me.

**Comment by 8a8al00ey** [comment]
> Yes, I am in Cloudbox, but not sure how I can find you or let you find me.

Cloudbox is no longer being developed most have switched over to Saltbox: https://discord.gg/ZN23egtp. You can find me there `Baba Looey#9275` there is a #plex_autoscan room
