### ISSUE TITLE
Error: peewee.OperationalError: no such table: scan_item   I am not getting a queue.db created, assume its related

### ISSUE THREAD

**Issue by jhr1948** [by275/plex_autoscan#18]
Hi, i'm going crazy trying to figure out what i'm doing wrong.  I cant get this fork to work on my ubuntu server (Linux Mint).

I setup a fresh setup (numerous times over the last 2 days) and i keep getting the error "Error: peewee.OperationalError: no such table: scan_item" for every file PAS recognizes.

Also, I noticed that there is no queue.db created, but I assume that its related to that.  I am uploading the snippet of the log that shows the behavior. 

Any help would be appreciated.

Thanks
[PAS_Log.txt](https://github.com/by275/plex_autoscan/files/10230368/PAS_Log.txt)

**Comment by 8a8al00ey** [comment]
If you want to use file based db make sure you included `--queuefile` arg in the CLI.

**Comment by jhr1948** [comment]
Adding the argument --queuefile seemed to fix it.

Quick question, i see the 2 commits added, should i manually fix those things in the db.py file?

**Comment by 8a8al00ey** [comment]
You can ignore the first. The second "works" if you want to use the in memory option but may not be the proper fix. I would wait for the repo owner to review and possibly fix it properly.
