### ISSUE TITLE
Cant determine the paths for the scanner

### ISSUE THREAD

**Issue by hackmonker** [by275/plex_autoscan#22]
Not sure where I am doing it wrong but I cant seem to understand how to make the paths for plex work. rn plex in running in a docker container, hotio to be exact. while plex autoscan is in native according to readme. so what should the paths for scanner and database be in config?

If I use the paths inside the docker then the autoscan cant see them and scanners are not exposed outside the container so what should I change or do?

**Comment by 8a8al00ey** [comment]
Have you read the docs, particularly https://github.com/by275/plex_autoscan/blob/master/docs/configuration.md#server-path-mappings ?

**Comment by hackmonker** [comment]
ah so I realized where the problems were. The plex user had to be root. I was trying out my normal user which was the problem

**Comment by hackmonker** [comment]
How to send a manual scan request now since no web ui is available? Like I want to send a scan to a filepath
