### ISSUE TITLE
Docker version? 

### ISSUE THREAD

**Issue by gurabli** [by275/plex_autoscan#23]
Thanks for keeping this version functional. The only one that has shared drive monitoring with encryption.
Do you have maybe a Docker version? If not, maybe possible to do one?
Thanks!

**Comment by by275** [comment]
Don't think it is impossible but quite complicated. No plan to add it but PR always welcomed.

**Comment by gurabli** [comment]
I use Docker a lot, but don't have any experience in creating one. The original version of PAS has a Docker image available - I use it now for years. I don't know how difficult is to create one.

**Comment by by275** [comment]
Let me know which docker image you are using so I can reference Dockerfile.

**Comment by gurabli** [comment]
> Let me know which docker image you are using so I can reference Dockerfile.

The version from PTS: https://github.com/sabrsorensen/alpine-plex_autoscan

Image tag: sabrsorensen/alpine-plex_autoscan:1df2c05

It works perfectly fine, have comfigured Shared Drive monitoring on encrypted mounts. The problem is, it can't be re-installed anymore (based on what I read) as G changed auth, something your version has fixed, if I'm correct. So if I need a new clean install (or migration to something else), I will not be able to install. And new Autoscan (A-Train) doesn't support encryption.

**Comment by by275** [comment]
Thanks. There's one thing I can't understand from README below

> Mounting the Docker API socket file is necessary for the plex_autoscan service to interact with Plex Docker containers.

Can you explain a little further on this?

**Comment by by275** [comment]
> Can you explain a little further on this?

Never mind. I figured out.

**Comment by gurabli** [comment]
Glad to hear. I don't know what that means. I use an automated deployment, so I never had to deal with that.

**Comment by by275** [comment]
Would you please test docker image using

```bash
docker run -d \
    -p 3467:3467 \
    --name=<container name> \
    -v <path for config files>:/config \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e PUID=<uid for plexautoscan user> \
    -e PGID=<gid for media group with access to your library> \
    -e TZ=<timezone> \
    ghcr.io/by275/autoscan:pr
```

I believe the usage is almost same as one from `sabrsorensen/alpine-plex_autoscan`.

**Comment by gurabli** [comment]
Nice, you made a docker version!
Atm I can't try it, very busy and don't have a test server up. But I'll give a ping to others I know are looking for this version.
Great work! I guess in this version the authentication for shared drive monitoring works, and it also supports encrypted mounts.
