### ISSUE TITLE
feat: checking file existence remotely

### ISSUE THREAD

**Issue by by275** [by275/plex_autoscan#32]
Plex media server provides an API for browsing media files.

Related:
 - API endpoint: `services/browse`
 - [python-plexapi reference](https://python-plexapi.readthedocs.io/en/latest/modules/server.html#plexapi.server.PlexServer.browse): `browse`, `walk`, `isBrowsable`

Due to a bug in the PMS system, we were unable to implement this feature. However, the bug has now been fixed, so we should reconsider implementing this feature, as it would allow autoscan logic to work remotely.

**Comment by CLHatch** [comment]
> Plex media server provides an API for browsing media files.
> 
> Related:
> 
> * API endpoint: `services/browse`
> * [python-plexapi reference](https://python-plexapi.readthedocs.io/en/latest/modules/server.html#plexapi.server.PlexServer.browse): `browse`, `walk`, `isBrowsable`
> 
> Due to a bug in the PMS system, we were unable to implement this feature. However, the bug has now been fixed, so we should reconsider implementing this feature, as it would allow autoscan logic to work remotely.

So am I correct in assuming that until this is done, we can't currently have Plex in one Docker container, and plex_autoscan in another?  I had previously used an old container that had the original plex_autoscan "embedded" in a Plex container, and it worked great, but I'm having trouble getting the Docker container from here to work with the LSIO Plex container.

**Comment by by275** [comment]
> So am I correct in assuming that until this is done, we can't currently have Plex in one Docker container, and plex_autoscan in another?

No, Plex Autoscan container should work if it can access the same media files as Plex. In other words, volume mapping to Plex Autoscan container and proper configuration for `SERVER_FILE_EXIST_PATH_MAPPINGS` are required.

If this feature is done, Plex Autoscan container can be deployed on any physical server.

**Comment by CLHatch** [comment]
> > So am I correct in assuming that until this is done, we can't currently have Plex in one Docker container, and plex_autoscan in another?
> 
> No, Plex Autoscan container should work if it can access the same media files as Plex. In other words, volume mapping to Plex Autoscan container and proper configuration for `SERVER_FILE_EXIST_PATH_MAPPINGS` are required.
> 
> If this feature is done, Plex Autoscan container can be deployed on any physical server.

Do you happen to have a Discord server or similar so I could get some help?  I would open an "issue" here, but it sounds like it's not a bug, it's me misconfiguring things, and I don't want to hijack your own FR here to get help. :)

**Comment by by275** [comment]
I was wrong. The bug is still there so we close this issue until it is resolved.
